[package]
name = "fascii"
version = "0.1.0"
authors = ["Zach Schuermann <zachary.zvs@gmail.com>"]
edition = "2018"
default-run = "fascii"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "fascii_bench"
harness = false
